deeplinkSpecs:
  - name: user profile
    description: "Opens the user profile screen"
    scheme: "myapp"
    host: "example.com"
    pathParams:
      - !<definedParam>
        key: profile
      - !<templateParam>
        key: id
        type: numeric
    queryParams:
      - key: ref
        type: alphanumeric
    fragment: section
  #    example: "myapp://example.com/user/123?ref=share#section"

  - name: Product Detail
    description: "Opens a product detail page"
    scheme: "myapp"
    host: "shop.example.com"
#    pathParams:
#      - name: productId
#        type: Int
#        required: true
#    example: "myapp://shop.example.com/product/42"