deeplinkSpecs:
  - name: user profile
    description: "Opens the user profile screen"
    scheme: "myapp"
    host: "example.com"
    pathParams:
      - name: profile
      - name: id
        type: numeric
    queryParams:
      - name: ref
        type: alphanumeric
    fragment: section

  - name: Product Detail
    description: "Opens a product detail page"
    scheme: "myapp"
    host: "shop.example.com"
    pathParams:
      - name: product
        type: alphanumeric
    fragment: reviews