deeplinkSpecs:
  - name: "open profile"
    activity: com.aouledissa.deepmatch.sample.MainActivity
    categories: [DEFAULT, BROWSABLE]
    scheme: [app]
    host: ["sample.deepmatch.dev"]
    pathParams:
      - name: profile
      - name: userId
        type: alphanumeric
    queryParams:
      - name: ref
        type: string
        required: true
    fragment: "details"

  - name: "open series"
    activity: com.aouledissa.deepmatch.sample.MainActivity
    categories: [DEFAULT, BROWSABLE]
    scheme: [app]
    host: ["sample.deepmatch.dev"]
    pathParams:
      - name: series
      - name: seriesId
        type: numeric
    queryParams:
      - name: ref
        type: string

  - name: "open hostless profile"
    activity: com.aouledissa.deepmatch.sample.MainActivity
    categories: [DEFAULT, BROWSABLE]
    scheme: [app]
    pathParams:
      - name: profile
      - name: profileId
        type: numeric
