deeplinkSpecs:
  - name: "open series"
    description: "Opens series details page"
    activity: com.aouledissa.deepmatch.sample.MainActivity
    autoVerify: true
    scheme: "https"
    host: ["joyn.de", "joyn.at"]
    pathParams:
      - name: series
      - name: seriesId
        type: alphanumeric

  - name: "open movies"
    description: "Opens movies details page"
    activity: com.aouledissa.deepmatch.sample.MainActivity
    autoVerify: true
    scheme: "https"
    host: ["joyn.de", "joyn.at"]
    pathParams:
      - name: filme
      - name: movieId
        type: alphanumeric
    fragment: "trailer-tab"

  - name: "open app"
    description: "Opens application with a deeplink"
    activity: com.aouledissa.deepmatch.sample.MainActivity
    autoVerify: true
    scheme: "https"
    host: ["joyn.de"]