deeplinkSpecs:
  - name: "open series"
    description: "Opens series details page"
    activity: com.aouledissa.deepmatch.sample.MainActivity
    autoVerify: true
    scheme: "https"
    host: "joyn.de"
    pathParams:
      - name: series
      - name: seriesId
        type: alphanumeric

  - name: "open movies"
    description: "Opens movies details page"
    activity: com.aouledissa.deepmatch.sample.MainActivity
    autoVerify: true
    scheme: "https"
    host: "joyn.de"
    pathParams:
      - name: filme
      - name: movieId
        type: alphanumeric